### ISSUE TITLE
Am I missing something?

### ISSUE THREAD

**Issue by mrpetenorth** [kdechant/eamon#10]
I go to create new adventurer, enter a name, select gender and begin adventuring career and enter the main hall.  I click on "Next" and then "go on an adventure".  I get the list of available adventures but there is no link to begin the quests.  Clicking on the quest name does nothing and there is no play button like on the demo adventures.

**Comment by kdechant** [comment]
One of the JavaScript files was not loading correctly. It was preventing adventurers from saving and going on adventures.

This is fixed now. Please try again. You might need to hit the "reload" button on your browser to make the game work correctly. And you'll need to create a new adventurer.
