### ISSUE TITLE
Get an error when trying to login with Facebook

### ISSUE THREAD

**Issue by altyrocks** [kdechant/eamon#110]
App Not Setup: This app is still in development mode, and you don't have access to it. Switch to a registered test user or ask an app admin for permissions.

**Comment by kdechant** [comment]
This is a known issue. I'm planning to look into it over the weekend.

If you were using the Facebook login to move your characters from one computer to another, and now you're locked out, just let me know the name(s) of your characters and I can help you recover them.

**Comment by msmeads** [comment]
Hello! I too am encountering this issue and am wondering if there is any update on this issue. I now have multiple shared devices with some new family members and it may be a challenge to keep contacting an admin with my list of character names whenever we want to play. 

I am hoping it is just a matter of releasing the Facebook app into production (non-development) mode, or if we could be added as test users for the app. Thank you.

**Comment by kdechant** [comment]
The Facebook login turned out to be too much work to maintain. I ended up replacing it with an access code that you can use to keep the same characters across different browsers and computers. Hopefully that will work well enough for everyone.
