### ISSUE TITLE
Issue with armors at the store

### ISSUE THREAD

**Issue by KevinRatelle** [kdechant/eamon#111]
![image](https://user-images.githubusercontent.com/11675478/148029136-c7e1b0bf-34ac-4edc-abbf-744ad8df2abb.png)

Just started a new adventurer. Went to the store, and the armors seem bugged. I was able to buy a leather armor nonetheless, but was unable to equip it. I tried to sell it and I would get the gold but would keep the item, causing a secondary bug where I could easily get infinite money.

**Comment by kdechant** [comment]
This is fixed.

It was incorrectly classifying armors (but not shields) as weapons when you bought them in the store, making it impossible to wear them. The infinite money bug was caused when I reworked some of the UI recently.
