### ISSUE TITLE
error saving a game

### ISSUE THREAD

**Issue by insomnimus** [kdechant/eamon#116]
Typing `save`, choosing a slot and giving a name like "asdf" tells me that the game is saved to slot N; however after the very next command it says `Error saving game!`

I'm playing on latest Firefox, Windows 10 with a screen reader (NVDA) running.

I wish I could provide more data but that's it.

**Comment by kdechant** [comment]
Which adventure were you playing when you noticed this?

**Comment by insomnimus** [comment]
Sorry for the late response. The adventure was The Beginners Cave.

**Comment by insomnimus** [comment]
I've tried one more adventure - the Training Grounds - the error still persists.

**Comment by insomnimus** [comment]
Update: Tried on Chrome and the same error happened.

**Comment by kdechant** [comment]
I figured it out. This was an issue that only affected players that were created within the last couple months. This is fixed now.
