### ISSUE TITLE
Can you save during play?

### ISSUE THREAD

**Issue by aubloom** [kdechant/eamon#16]
Sorry if I missed this feature somewhere in the interface, but are you able to save a game in progress, like in Eamon Deluxe? Or can you only save between adventures?

**Comment by kdechant** [comment]
That feature doesn't currently exist, but I'm working on it.

**Comment by kdechant** [comment]
At long last, I have completed the saved game feature. You can now save your game by typing the SAVE command during game play. To restore a saved game, you can type RESTORE and choose the save slot you want to restore.

If your character meets an untimely end during play (that fiendish Donald Brown was known for his no-warning death traps!) you will be prompted to restore a saved game. Also, if you saved your game and then closed your browser window, the next time you visit Eamon and load up your character, you will see a list of saved games. This is useful for the longer adventures which may take more than one session to finish.

**Comment by aubloom** [comment]
Thanks for the update Keith. That's a big one. I'll probably post about
this in my IF blog in the semi-near future.

-Wade
