### ISSUE TITLE
Trying to buy with non enough money give you negative money

### ISSUE THREAD

**Issue by Alby1987** [kdechant/eamon#2]
Hi!

If you roll a new adventureer (starting with 200 GP), and trying to buy a spell costing 1000GP, the wizard will tell you the money you have are not enough, but your characters goes from 200 to -800.

Hope it's clear :)

Keep on good work!
Alby

**Comment by kdechant** [comment]
This is fixed. Also fixed a similar issue in Marcos' weapons shop.
