### ISSUE TITLE
Facebook and browser issue

### ISSUE THREAD

**Issue by kpeamon** [kdechant/eamon#20]
I could not log in with facebook. I get the following error (translated):  "App not configured. Still under development.  Ask app-administrator for permission".
This happened with Microsoft Edge and Internet Explorer.

I then tried Chrome to see if that would work. But apparently, I cannot enter the main hall anymore with Chrome. It just says: "Welcome to the Wonderful World of Eamon..." and nothing happens after that.

All of the above was done with Windows 10.

**Comment by kdechant** [comment]
I'll bet you're using the old domain name (eamon.terranok.com) which isn't set up to work with the Facebook login (an oversight on my part, and a tricky one to fix as Facebook won't allow multiple separate domains for the same app).

Can you go to the new domain (https://eamon-remastered.com) and try it there? You won't see any of your existing characters, but I can help you recover them once we know that the Facebook login works.

**Comment by kpeamon** [comment]
I was using https://eamon-remastered.com when I experienced the Facebook error. I did not know about Eamon.terranok.com until now. I have just tried both domains without luck.

**Comment by kpeamon** [comment]
FB login still not working - tried logging out of facebook first but that didn't help. Sounds from the error message that I need to be an approved test-user. Note that I am logging in from Denmark - not sure if that matters.

I did get the main hall working on Chrome though, by clearing the cache, but FB login does not work for me on Chrome either.

**Comment by kpeamon** [comment]
I haven't played Eamon for a very long while. But I tried recently and everything works very well now, so I guess it is time to close this issue.
