### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by damienhurrell** [kdechant/eamon#27]
Sometimes when playing, there are many lines of text describing the result of each command.  This is most especially true during a battle with many monsters with a large party.  Previous versions of Eamon handled this by posting one page of text then awaiting a keystroke to post the next page.  This could be annoying, especially when the next page was a single blank line, but had the advantage of ensuring the player could scan everything that happened.  I assume that because Eamon Remastered includes an interface that allows the player to scroll up to review information, it doesn't have the page by page output feature.

However, I also find this frustrating.  Because the player attack always happens first, I have to scroll up after every round to see the result of my attack.  I find this slows the combat and detracts from the experience.  Is it possible to restore the pagination?

**Comment by kdechant** [comment]
That's been a frustration for me, as well. Pagination in the old-school "press a key to continue" way isn't really possible with the web interface. An older version of the code had a delay that would make the text appear more slowly, giving you a chance to read it, or at least see it scroll by so you could review if you wanted. That broke when I revised the UI back in fall and I haven't had a chance to find an alternate solution. Still looking for one.

**Comment by kdechant** [comment]
I recently released an improvement to the way the results are displayed. There is now an automatic pause in the output once a certain amount of text has been displayed. It's not foolproof, but I think it's a big improvement to the previous logic.
