### ISSUE TITLE
Are maps spoilers or helpful?

### ISSUE THREAD

**Issue by chiperific** [kdechant/eamon#28]
As I play through adventures, I'm creating maps for my own benefit. Just location names and visible exits.

I'm not well versed in the IF world. Is sharing these maps to source code a beneficial addition or a faux pas?

**Comment by kdechant** [comment]
I think it's usually OK to include spoilers as long as there's a warning to the user, so they don't accidentally see anything they don't want to. Some of the in-game hints have spoilers, which I blurred out until the user clicks them.

It would probably be fairly easy to include PDFs or even Trizbort map files as downloadable links from the adventure page. There's already a way to store assets within the adventures, currently only used for this image which appears on the Caves of Treasure Island intro screen: https://github.com/kdechant/eamon/blob/master/adventure/static/adventures/the-caves-of-treasure-island/treasure-island-map.png

If I had all the time in the world, I would try to implement an in-game automap, which would be really cool and also sounds like a ton of work. Margaret Anderson (author of several Eamon adventures) actually built one on the Apple II a few years ago, but I don't know how to get the source code.

**Comment by damienhurrell** [comment]
Maps for nearly every adventure are already available online at http://www.eamonag.org/maps/eamon_maps2.htm

I tend to regard the making of a map part of the joy of the exploration, and only use the published maps  if I'm irredeemably stuck. The reason I avoid them when exploring is that maps show secret passages, destroying the joy of looking for and finding those features.  As such, I regard them as spoilers and wouldn't want them to be routinely included.  

But like the potential spoilers in the hints, they can head off frustration as well.  When you miss the clues to a secret passage the first time you enter a room, it can be very tedious to look or examine every room description to find the secret that was missed.  So I agree that treating the same way as the existing hints has merit.

I wish I had the time and programming skills to help write an automapping feature. It does sound really cool.
