### ISSUE TITLE
Beginners Cave Errors

### ISSUE THREAD

**Issue by EamonAG** [kdechant/eamon#3]
Was able to enter the adventure with more than one weapon.
The mimic shouldn't allow you to flee.
Cynthia listed as a neutral for charisma of 8. She should be friendly.

**Comment by kdechant** [comment]
Just like Eamon Deluxe, the "are you a beginner?" checks are disabled for Beginner's Cave and Beginner's Forest. The knight marshal still warns you but he lets you proceed anyway.

I checked the database and Cynthia has a friendliness of 95%, which is the same as Eamon Deluxe. This does seem strange, though, so I'll have to change her to be "always friendly".

There are several monsters in various adventures that should prevent you from fleeing. (The shark in Furioso and the cesspool monster in Magic Kingdom come to mind.) This is common enough that I think I'll have to add a flag to the monster definition in the database.

**Comment by kdechant** [comment]
I updated the Knight Marshal's dialog a little if you enter while not a beginner, but I'm not planning on preventing characters from entering with two weapons, etc. just yet.

I fixed fleeing the mimic.

I also changed Cynthia to "always friendly" to avoid the ~5% chance she would end up neutral.
