### ISSUE TITLE
The Indefinite Article

### ISSUE THREAD

**Issue by damienhurrell** [kdechant/eamon#34]
Played through and enjoyed The Quest for the Holy Grail: found it true to the film and fun to play.

The only quibble I have is that many of the names for monsters and items seem to include the indefinite article: thus "The Black Knight" or "The Holy Hand Grenade" or "an inscription".  While "The Black Knight" is canonically correct, for most of the others, the article is just an annoyance that means that a command like "read inscription" fails.  Can I suggest that deleting the indefinite article from most of the descriptions would help with gameplay?

**Comment by kdechant** [comment]
Articles were added to some artifacts and monsters to make the text read more smoothly in some places. However, you're right that it was interfering with commands. I tend to use a lot of abbreviated commands when I play (e.g., AT BL for ATTACK THE BLACK KNIGHT) and the articles were inconvenient in that situation.

I just released an update which changes the logic on the way articles are handled before artifact and monster names. You can now ignore the article name completely when typing. E.g., "ATTACK BLACK" will still work even if the word "the" appears before his name.

FYI, you can also do partial word matching at the end of artifact and monster names. e.g., "OPEN CHE" and "OPEN ST" both work for opening an artifact named "chest". However, if the name has more than one word, it only works on the beginning of the first word and the end of the last word. So, "ATTACK GI" wouldn't work for "ATTACK FROST GIANT" but "ATTACK FR" or "ATTACK NT" would.
