### ISSUE TITLE
Temple of Ngurct item damaging

### ISSUE THREAD

**Issue by Shin-Ji** [kdechant/eamon#35]
In the Temple of Ngurct, there seems to be a problem that once the fifth or so item it picked up by the player, the player takes damage from each one picked up. It says "Alignment Conflict, the evil runes on the scimitar burn with a cold fire on your hand!"

But no scimitar had been encountered at that point. By the way, thanks for the work!

![2019-07-07_13-11-01](https://user-images.githubusercontent.com/43322437/60771677-5f504200-a0b9-11e9-93cf-5cf36f4b6394.png)

**Comment by kdechant** [comment]
This was a typo in the code. It's fixed now.
