### ISSUE TITLE
Cannot pass through a trap in Nguret

### ISSUE THREAD

**Issue by Shin-Ji** [kdechant/eamon#36]
When you go down and through the oak door that locks behind you, and move north three spaces, there's a room with some holes in the wall that sprays gas at you. There seems to be a typo in the code for that room, because it's impossible to leave it once you enter.
![firefox_2019-07-24_12-18-55](https://user-images.githubusercontent.com/43322437/61810907-52985180-ae0e-11e9-964d-4cd8c716666c.png)

**Comment by Shin-Ji** [comment]
This was done with an updated Firefox browser on a PC, by the way.

**Comment by kdechant** [comment]
That was a weird one. That particular trap can target up to three monsters. However, if there were fewer than three monsters in the room, it would go on trying to select another target and fail.

Fixed.
