### ISSUE TITLE
Assault on the Clone Master bugs

### ISSUE THREAD

**Issue by kpeamon** [kdechant/eamon#39]
This is a good game, but there are two serious bugs in this game. You can enter the fortress through the east and west walls, without blowing up the dynamite. In location "outside the west wall" you simply go east, and in location "Outside the east wall" you simply go west. Furthermore, the crack on the east side and the crack on the west side can both be opened, simply by typing "open crack". After doing so, you can also "close crack".

**Comment by kdechant** [comment]
Fixed.

This was due to some upgrades I made to the door handling logic for other adventures. I apparently hadn't updated this adventure to work correctly.
