### ISSUE TITLE
Minotaur error

### ISSUE THREAD

**Issue by EamonAG** [kdechant/eamon#4]
Check this transcript after Lil died:

power
Nothing happens.
In the Gypsy camp. (N/S/E/W)
You see Larcenous Lil's body.

power
Nothing happens.
In the Gypsy camp. (N/S/E/W)
You see Larcenous Lil's body.

heal lil
Spell ability increased!
Some of Larcenous Lil's wounds seem to clear up.
Larcenous Lil is in pain.

In the Gypsy camp. (N/S/E/W)
Larcenous Lil is here.
You see Larcenous Lil's body.

**Comment by kdechant** [comment]
That was a good one. The HEAL spell logic contained a check if the monster was in the room but it wasn't working. I updated the code and also added a "no one here by that name" message if you try to heal a monster that isn't in the room.
