### ISSUE TITLE
Abductor's Quarters

### ISSUE THREAD

**Issue by EamonAG** [kdechant/eamon#5]
1. Can't go west from "west treasure chamber." I get a message "Error: Cannot read property 'id' of null".
2. Can't ready a weapon if one isn't ready. I also get the message "Error: Cannot read property 'id' of null"

**Comment by kdechant** [comment]
Both of these items are fixed.

The west treasure chamber was just an incorrect room connection. I had removed a room from that area and missed one connection that needed to be updated.

The error when readying a weapon was a bug in this adventure's event handlers and didn't affect any other adventures.
