### ISSUE TITLE
Finding the secret passage in the Abductor's Throne Room

### ISSUE THREAD

**Issue by damienhurrell** [kdechant/eamon#50]
Not a bug exactly, more of a matter of style:

The description of the Throne room in the Abductor's Quarters is:

"You are in a very large room. On the south wall is a large, fancy throne bedecked in blood-red drapes. Gold statues stand on either side of the throne. In the middle of the room is a fine oak table with what appear to be blood stains. A jewel-encrusted goblet rests on the table."

I examine the table, the goblet the throne and the drapes.  Nothing helpful.

But if I examine south, then:

"You find a hidden button on the throne which causes part of the south wall to open!"

To my mind, a puzzle isn't about finding the exact right command, it's about realising that there's something important and looking in the right place.  So I think that an adventurer who examines the throne (as well as one who examines the south wall) should find the button and the secret passage. 

Sometimes authors are right to require specificity and accuracy, for example, when saying magic words.  Sometimes the code needs to accommodate the fact that different people write the same basic request in different terms.

I think this case is the latter.

**Comment by kdechant** [comment]
Fixed. Examining the throne is the intended way to find that secret door. I'm definitely trying to avoid the "guess the command" situation in most cases. This is just one I missed when porting the adventure.

I updated a few room descriptions and artifact properties as well, trying to polish a few of the remaining rough edges.

I also scaled back the difficulty a little, as I seem to get horribly killed every time I play this adventure, even with an experienced character and liberal use of the HEAL and SPEED spells. (This was true of the Apple II original, as well. It's the layout of the adventure; you have to fight almost everyone in the place before you meet any friendly NPCs.)
