### ISSUE TITLE
Recall previous commands

### ISSUE THREAD

**Issue by damienhurrell** [kdechant/eamon#51]
Running a new character through the beginner's cave, I noticed the following message:

"You see some words chiseled into the wall: "To repeat the last command, just hit the Enter key again. To recall previous commands, use the up and down arrow keys.""

The first part of this works for me, but the second part doesn't: the arrow keys have no effect.

In Chrome version 80.0.3987.163

**Comment by kdechant** [comment]
Fixed. The command recall with the arrow keys was working sometimes, notably at the beginning of each adventure. It would slowly start misbehaving the longer you played. It turns out that the recall logic was getting confused when the same command was run multiple times in a row.
