### ISSUE TITLE
end of adventure bug

### ISSUE THREAD

**Issue by damienhurrell** [kdechant/eamon#53]
I had a wander through the Abductor's Cave to test recent changes. All good.

However, when I got back to the Sam Slicker page I decided to downgrade my rating of the combat.  When I did, I was immediately jumped to the home page. Re-entering the main hall, I noticed that my character hadn't been credited with the gold earned and attribute increases has disappeared as well.

It's not isolated to one adventure so I assume the bug's in the code for the ratings

**Comment by damienhurrell** [comment]
Had the same crash behaviour when clicking the "how to enter commands" link in the command list (in multiple adventures)

**Comment by kdechant** [comment]
Fixed. It had been months since I touched that ratings code, so I'm guessing this was caused by either a React framework update or some changes in recent browser versions.
