### ISSUE TITLE
missing key?

### ISSUE THREAD

**Issue by damienhurrell** [kdechant/eamon#58]
In the cliffs of Fire adventure I cannot find a key to open the locked door on the second level of the tower.

Am I missing something or is something missing?

PS: Yes, I'm escaping isolation by visiting Eamon.

**Comment by kdechant** [comment]
It's in the sarcophagus on level 2. Each level of that tower is pretty self-contained and has everything you need to get to the next level, if you can find it.

I do see that there are no hints for that adventure. I'll have to add some.

**Comment by damienhurrell** [comment]
Found it. Thanks
