### ISSUE TITLE
Chest hidden in furniture (Attack of Kretons)

### ISSUE THREAD

**Issue by damienhurrell** [kdechant/eamon#59]
I missed the chest that contains a vital element because I typed the command "ex furn" rather than "ex furniture".

Another "guess the command" moment I think.

![furniture](https://user-images.githubusercontent.com/47295628/80274122-7c730180-871b-11ea-85ce-da5a49fc9f13.png)

**Comment by kdechant** [comment]
Fixed. The "synonym" logic that allows alternate names for objects (in this case "furniture" is an alternate name for "chest") was not working with partial word matches.

**Comment by damienhurrell** [comment]
I suspect that's what happened with the mirror in the devil's dungeon, too.
