### ISSUE TITLE
Conflicting directions

### ISSUE THREAD

**Issue by damienhurrell** [kdechant/eamon#60]
In the Well of the great Ones, the description of the crypt of regret shows different exits to what is available
![CRYPT OF REGRET](https://user-images.githubusercontent.com/47295628/80295136-834d5300-87b3-11ea-8e7d-d713921fc822.png)

**Comment by damienhurrell** [comment]
Similar issue in the Temple of Ngurct:
![Temple ngurct](https://user-images.githubusercontent.com/47295628/80438729-2df67a80-8948-11ea-8567-84c51d330783.png)

**Comment by kdechant** [comment]
These are fixed.

There is actually new logic in the adventure code to insert the movement directions automatically based on the exits the player can see, including secret doors that have been found. But, I haven't converted all the adventures to it yet. So there are bound to be a few mistakes in the ones like these that were manually entered into the room name.
