### ISSUE TITLE
Unopenable secret entrance?

### ISSUE THREAD

**Issue by damienhurrell** [kdechant/eamon#64]
In Demongate, there is a bricked up wall at the bottom of the spiral staircase that screams secret entrance to me. But examination, attack, power, blast and charging the wall all fail to reveal or open it.  I don't recall a magic word or a suitable tool and the earthquake scroll doesn't help either. No hints available.

there's a similar wall in the large room down from the hot chapel, which is similarly unresponsive.

What gives?

**Comment by kdechant** [comment]
IIRC, that bricked up doorway was there in the original, and meant to show signs of recent construction. I think you can get to the other side of it via a different tunnel, but there's no way through.

**Comment by damienhurrell** [comment]
Thanks
