### ISSUE TITLE
What to do with the Ankh? 

### ISSUE THREAD

**Issue by damienhurrell** [kdechant/eamon#65]
The text in Demongate talks about preventing the indestructible ankh from falling into the wrong hands.  It's not apparent to me how that could be done, and there's no hints. I tried putting it into the wall of runes both before and after it's collapsed but no good.

**Comment by kdechant** [comment]
You're supposed to take it with you when you leave. I updated some text to make that more clear, and also to explain what happens to it when you bring it back to the Main Hall.
