### ISSUE TITLE
Gender flipping

### ISSUE THREAD

**Issue by damienhurrell** [kdechant/eamon#68]
In the Last Dragon, once I'd had my gender changed, it changed EVERY SINGLE TURN till the end. Which considering I took at least an hour to map the forest was a LONG time.  It got pretty boring.

I don't think it was something I was holding or wearing, so I wonder if the coding missed a termination point?  Or if it was artifact driven, perhaps a hint to help stop it occurring might be in order?

**Comment by kdechant** [comment]
That was an "equals" that should have been a "not equals". It's fixed now, along with a few other quirks I found in that adventure.
