### ISSUE TITLE
Devil's Dungeon

### ISSUE THREAD

**Issue by EamonAG** [kdechant/eamon#7]
I think the crystal ball is messing up. Going south from the dragon's lair, with the crystal ball, suddenly, every monster in the dungeon, both dead and alive, appeared in the room with me. As I killed them off, none of the dead monsters appeared. Tried again, same result. Dropped the crystal ball, went south, and all of their dead bodies and weapons were there. Picked up the crystal ball, went s, and all of the monsters appeared again, with their dead bodies in the same room as they were (the n/s corridor).

Afterwards, I couldn't give an object (the crystal ball) to someone as they are listed as not being in the room with me. I'm wondering if the crystal ball's antics are bringing monsters in, but somehow the program is not recognizing that they are in the room for "giving" purposes.

**Comment by kdechant** [comment]
This is fixed. I had an = in an if statement when it should have been ==. That was causing the monsters to all move to whatever room you were entering.
