### ISSUE TITLE
Zorag: Boris in the Trollsfire Pub does not understand "Say yes"

### ISSUE THREAD

**Issue by kpeamon** [kdechant/eamon#77]
I enjoyed the Eamon Deluxe version of **The Treachery of Zorag** very much and have been looking forward to the Eamon Remastered version.

However, there seems to be a bug in the **Trollsfire Pub**:

When I enter, Boris asks if I want to join him on an adventure. In the Eamon Deluxe version, I should just type **"say yes"** but in Eamon Remastered, Boris does not react to that command.

I have tried to **SAY YES** and **SAY YES TO BORIS** and simply **YES** but none of these works. I tried typing **SAY YES** right after I entered the pub and also tried the three sentences above right after **TALK TO BORIS** but nothing seems to work.

**Comment by kdechant** [comment]
That was a decision I made when porting the adventure. When playing through the EDX version of Zorag, "SAY YES TO BORIS" wasn't obvious to me and I got stuck on that plot point. So I made it just prompt the player to let Boris join whenever they ask about "adventure" or "treasure".

That said, it was easy enough to add "yes" to the keyword list, in case anyone else who played the EDX version tries the old command. Done.
