### ISSUE TITLE
Monsters Won't Wake Up!

### ISSUE THREAD

**Issue by thehendle** [kdechant/eamon#79]
Hello! First off, I've been having a lot of fun playing these adventures; back in the Apple ][ days I only had 3 Eamon disks (though it inspired me to learn enough basic to cobble some of my own together)

So I was playing Furiosa and I left the island but something glitched in my browser. When I restarted it, I could load my character ("The Hendle") and it put me in the main hall, but now I can't go on _any_ adventures. It gets stuck saying "Waking Up Monsters".

I tried with the generic "Brigette" character and they worked fine, so it must be something with my character. 

Thanks again!

**Comment by kdechant** [comment]
I don't see anything obviously wrong with your character, but if it gets stuck on "Waking up the monsters" that means there's probably a JavaScript error. Can you open your browser's console (usually with the F12 key) and see if there are any red errors in the Console tab?

**Comment by thehendle** [comment]
Thanks for your reply! Here's a copy-paste of what the Console shows. I'm using Firefox if this has any bearing. 

Loading failed for the <script> with source “https://www.googletagmanager.com/gtag/js?id=UA-87327244-2”. lair-of-the-minotaur:9:1
Uncaught (in promise) TypeError: this.saved_games[e] is undefined
    restore https://eamon-remastered.com/static/adventures/lair-of-the-minotaur.8e9413d53582.js:8
    init https://eamon-remastered.com/static/adventures/lair-of-the-minotaur.8e9413d53582.js:8
    componentDidMount https://eamon-remastered.com/static/core.ca279f731817.js:81
    promise callback*window.core</y</t.prototype.componentDidMount https://eamon-remastered.com/static/core.ca279f731817.js:81
    is https://eamon-remastered.com/static/core.ca279f731817.js:59
    dl https://eamon-remastered.com/static/core.ca279f731817.js:59
    unstable_runWithPriority https://eamon-remastered.com/static/core.ca279f731817.js:67
    $o https://eamon-remastered.com/static/core.ca279f731817.js:59
    pl https://eamon-remastered.com/static/core.ca279f731817.js:59
    Zs https://eamon-remastered.com/static/core.ca279f731817.js:59
    Gs https://eamon-remastered.com/static/core.ca279f731817.js:59
    Ll https://eamon-remastered.com/static/core.ca279f731817.js:59
    Hl https://eamon-remastered.com/static/core.ca279f731817.js:59
    tl https://eamon-remastered.com/static/core.ca279f731817.js:59
    Hl https://eamon-remastered.com/static/core.ca279f731817.js:59
    render https://eamon-remastered.com/static/core.ca279f731817.js:59
    core https://eamon-remastered.com/static/core.ca279f731817.js:81
    n https://eamon-remastered.com/static/core.ca279f731817.js:1
    core https://eamon-remastered.com/static/core.ca279f731817.js:1
    <anonymous> https://eamon-remastered.com/static/core.ca279f731817.js:1
lair-of-the-minotaur.8e9413d53582.js:8:9768
Source map error: Error: request failed with status 404
Resource URL: https://eamon-remastered.com/static/css/bootstrap.min.a15c2ac3234a.css
Source Map URL: bootstrap.min.css.map

**Comment by kdechant** [comment]
I think your browser is trying to load a previous saved game that has since been deleted. (Saved games normally get deleted automatically when you finish an adventure.) Perhaps related to whatever browser crash you had.

I just pushed a fix that should detect this condition and avoid trying to reload the saved game. Give that a try and see if it works.

**Comment by thehendle** [comment]
Still stuck, but the console error looks a little different:
oading failed for the <script> with source “https://www.googletagmanager.com/gtag/js?id=UA-87327244-2”. the-beginners-cave:9:1
Uncaught (in promise) TypeError: this.current_entry is undefined
    write https://eamon-remastered.com/static/adventures/the-beginners-cave.83f2a12a4f5e.js:8
    restore https://eamon-remastered.com/static/adventures/the-beginners-cave.83f2a12a4f5e.js:8
    init https://eamon-remastered.com/static/adventures/the-beginners-cave.83f2a12a4f5e.js:8
    componentDidMount https://eamon-remastered.com/static/core.ca279f731817.js:81
the-beginners-cave.83f2a12a4f5e.js:8:26914

​

**Comment by kdechant** [comment]
That should be easy to fix. Try it now.

**Comment by thehendle** [comment]
Thank you! That worked! I popped into the Beginner's Cave and it displayed an "Error Restoring Game" message before proceeding onto the game. I left and jumped back in once more for science and it worked perfectly, no error message the second time. 
I appreciate your help!
