### ISSUE TITLE
Zorag: Lantern / darkness problem

### ISSUE THREAD

**Issue by kpeamon** [kdechant/eamon#80]
I just completed The Treachery of Zorag (great game) and found one more bug.
Here is a short transcript:

> Your lantern just went out!
> It's too dark to see anything.
> NORTH
> You light the lantern before proceeding into the dark.
> Your lantern is almost out!

As you can see, when I proceed to a dark location, the lantern is turned on again, even though it ran out of fuel. I could keep playing like this even though I had used up all the lamp oil.
Very much related to this, in the Eamon Deluxe version it was possible to run around in the dark but you couldn't see anything. This was the only way I was able to complete the Eamon Deluxe version as I would have lacked lamp fuel in important locations. Thus, if you prevent the player from running around in the darkness when the lantern is out of fuel, please make sure that there is enough lamp fuel in the game, so the game can be completed. I think there wasn't enough in the Eamon Deluxe version but I managed by walking around in the dark in known places, and in this way I saved fuel for important situations.

**Comment by kdechant** [comment]
This is fixed.

According to Derek, the lamp oil situation in the EDX version was a bug. I revised the shopping logic a bit, so now you can buy as much lamp oil as you need. The shop will never run out. You can even buy it multiple times in a row and it will just add to the quantity that you're carrying.
