### ISSUE TITLE
Missing feature

### ISSUE THREAD

**Issue by EamonAG** [kdechant/eamon#9]
One thing that I miss is the ability to inventory my companions. This would let me know what they were carrying and know what their health status is. It was implemented in DDD7.0, did it not carry over into EDX?

**Comment by kdechant** [comment]
Yes, that would be useful, and was present in EDX also. I just never added an "inventory" command because you can see your inventory in the right sidebar. But that doesn't show you an NPC's inventory, so I'll need to add it after all. I'm planning to implement that feature soon.

**Comment by EamonAG** [comment]
You could have it pop up when you examine someone and that would make sense.
>Examine hermit
A grizzled old hermit is here.
He seems to be carrying <INVENTORY>
He is at death's door knocking loudly <1/19 HP>

**Comment by kdechant** [comment]
I added the inventory and health status to monsters when you LOOK at them. For friendly monsters you'll see their full inventory. For neutral and hostile monsters, you'll only see their ready weapon.
